import {initializeApp} from 'firebase/app';
import {getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged,browserSessionPersistence,setPersistence,getIdTokenResult} from 'firebase/auth';
import {getFirestore,collection,doc,getDocs,query,where,limit,runTransaction,writeBatch,serverTimestamp,setDoc,updateDoc} from 'firebase/firestore';
import {getStorage,ref,uploadBytes,getBlob} from 'firebase/storage';
import {nextQuota} from './quota.js';
import {firebaseConfig,site} from './config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);
const root=document.querySelector('#editorial-app');const params=new URLSearchParams(location.search);
const editorMode=document.body.dataset.mode==='editor';
const el=(tag,text,attrs={})=>{const e=document.createElement(tag);if(text)e.textContent=text;for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;};
const status=el('p','',{role:'status'});let user,editor=false,draftId=null,submissions=[],drafts=[],publications=[];
const formError=e=> e.code==='permission-denied'?'Please check your access or try later. Submissions are limited to one per minute and ten per hour; your writing is still here.': e.code==='auth/popup-closed-by-user'?'Sign-in was cancelled.':e.code==='auth/popup-blocked'?'Please allow the sign-in window and try again.':'Unable to complete that action. Please try again. Your writing remains in the form.';
const button=(text,action)=>{const b=el('button',text,{type:'button'});b.onclick=async()=>{b.disabled=true;status.textContent='';try{await action();}catch(e){status.textContent=formError(e);}finally{b.disabled=false;}};return b;};
function field(form,label,name,{type='text',value='',max=240,required=true}={}){const l=el('label',label),input=el(type==='textarea'?'textarea':'input');input.name=name;input.id='field-'+name;if(type!=='textarea')input.type=type;input.value=value;input.required=required;input.maxLength=max;l.htmlFor=input.id;form.append(l,input);return input;}
function select(form,label,name,options,value){const l=el('label',label),input=el('select');input.name=name;input.id='field-'+name;l.htmlFor=input.id;for(const [v,t]of options){const o=el('option',t,{value:v});input.append(o);}input.value=value;form.append(l,input);return input;}
function base(){root.replaceChildren();const actions=el('div','',{class:'editorial-actions'});actions.append(el('span',user?.email||''),button('Sign out',()=>signOut(auth)));root.append(actions,status);status.textContent='';}
async function login(){await setPersistence(auth,browserSessionPersistence);await signInWithPopup(auth,new GoogleAuthProvider());}
onAuthStateChanged(auth,async current=>{user=current;root.replaceChildren();if(!current){root.append(el('p',editorMode?'Sign in with your editor account.':'Sign in to send writing to the editors. Reading the magazine never requires an account.'),button('Continue with Google',login),status);return;}
try{editor=!!(await getIdTokenResult(current,true)).claims.editor;base();if(!current.emailVerified){status.textContent='A verified Google email is required.';return;}if(editorMode){if(!editor){status.textContent='This account does not have editor access.';return;}await dashboard();}else await submissionForm();}catch(e){status.textContent=formError(e);}});
async function submissionForm(){const kind=['article','comment','contact','book'].includes(params.get('kind'))?params.get('kind'):'article';
 const form=el('form');form.append(el('h2',kind==='comment'?'ଆପଣଙ୍କ ମତାମତ / Your comment':kind==='contact'?'ଯୋଗାଯୋଗ / Contact':kind==='book'?'Book enquiry':'ଲେଖା ପଠାନ୍ତୁ / Send to the editor'));
 if(kind==='book')form.append(el('p','Ask the publisher about availability or ordering. This sends an enquiry; it does not place a paid order.'));
 const name=field(form,'ନାମ / Name for your byline','name',{value:user.displayName||'',max:120});
 field(form,'Email (private)','contact',{type:'email',value:user.email,max:254}).readOnly=true;
 field(form,'ଶୀର୍ଷକ / Title','title',{value:(params.get('title')||'').slice(0,240)});
 field(form,'ଲେଖା / Your writing or message','body',{type:'textarea',max:kind==='comment'?2000:60000});
 let file;if(site.uploadsEnabled){file=field(form,'Optional manuscript (PDF, DOCX or text; up to 10 MB)','attachment',{type:'file',required:false});file.accept='.pdf,.docx,.txt';}else form.append(el('p','Paste your writing above. File attachments are not enabled yet.'));
 const consent=el('label','',{class:'editorial-consent'}),check=el('input',null,{type:'checkbox',required:''});consent.append(check,el('span','I have permission to submit this work. Editors may contact me and review it. Only approved writing and the byline may become public. Children should ask a parent or teacher to help.'));form.append(consent);
 const send=el('button','Send for review',{type:'submit'});form.append(send);root.append(form);
 form.onsubmit=async e=>{e.preventDefault();if(!form.reportValidity())return;send.disabled=true;status.textContent='Sending…';let sent=false;
 try{const data=new FormData(form),attachment=file?.files[0];if(attachment&&(attachment.size>10*1024*1024||!['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain'].includes(attachment.type)))throw Error('attachment');
 const item=doc(collection(db,'submissions'));const page=params.get('page')||'';await runTransaction(db,async batch=>{const quota=doc(db,'submissionLimits',user.uid),q=await batch.get(quota);
 batch.set(item,{owner:user.uid,name:name.value.trim(),contact:user.email,kind,title:String(data.get('title')).trim(),body:String(data.get('body')).trim(),page:page.startsWith(site.prefix+'/')?page.slice(0,300):'',status:'received',consent:'editorial-review-v1',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
 batch.set(quota,nextQuota(q.data(),{id:item.id}));});sent=true;
 if(attachment){try{await uploadBytes(ref(storage,`submissions/${user.uid}/${item.id}/manuscript`),attachment,{contentType:attachment.type});}catch{status.textContent='Your writing was received, but the attachment failed. Reference: '+item.id;form.querySelector('[name=body]').value='';await ownSubmissions();return;}}
 status.textContent='Received for private editorial review. Reference: '+item.id;form.querySelector('[name=body]').value='';if(file)file.value='';await ownSubmissions();
 }catch(e){status.textContent=e.message==='attachment'?'Choose a PDF, DOCX or text file smaller than 10 MB.':formError(e);}finally{send.disabled=false;}};
 await ownSubmissions();}
async function ownSubmissions(){root.querySelector('#my-submissions')?.remove();const section=el('section',null,{id:'my-submissions'});section.append(el('h2','Your submissions'));const snapshot=await getDocs(query(collection(db,'submissions'),where('owner','==',user.uid),limit(50)));const items=snapshot.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));if(!items.length)section.append(el('p','No submissions yet.'));for(const d of items)section.append(el('p',`${d.title} — ${d.status}`));root.append(section);}
async function dashboard(){root.querySelector('#dashboard')?.remove();const panel=el('div',null,{id:'dashboard'});root.append(panel);
 const [a,b,c]=await Promise.all(['submissions','drafts','publications'].map(name=>getDocs(query(collection(db,name),limit(200)))));submissions=a.docs.map(d=>({id:d.id,...d.data()}));drafts=b.docs.map(d=>({id:d.id,...d.data()}));publications=c.docs.map(d=>({id:d.id,...d.data()}));
 panel.append(el('p','Private submissions and drafts are visible only to editors. Publish releases the approved text and byline; contact details stay private. Website updates usually appear within 30 minutes.'));
 const actions=el('div',null,{class:'editorial-actions'});actions.append(button('Refresh',dashboard),button('New draft',()=>editDraft({})));panel.append(actions);
 panel.append(el('h2','Submissions'));if(!submissions.length)panel.append(el('p','No submissions yet.'));
 for(const d of submissions.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0))){const card=el('article',null,{class:'editorial-card'});card.append(el('h3',d.title),el('p',`${d.name} · ${d.kind} · ${d.status}`),el('p','Private contact: '+d.contact));const details=el('details'),summary=el('summary','Read submission');details.append(summary,el('pre',d.body));card.append(details);const actions=el('div',null,{class:'editorial-actions'});
 actions.append(button('Review',async()=>{await updateDoc(doc(db,'submissions',d.id),{status:'reviewing',updatedAt:serverTimestamp()});await dashboard();}));
 if(d.kind!=='contact')actions.append(button('Prepare draft',()=>editDraft({id:d.id,sourceId:d.id,kind:d.kind,title:d.title,body:d.body,byline:d.name,page:d.page})));
 actions.append(button('Decline',async()=>{await updateDoc(doc(db,'submissions',d.id),{status:'rejected',updatedAt:serverTimestamp()});await dashboard();}));
 if(site.uploadsEnabled)actions.append(button('Open manuscript',async()=>{try{const blob=await getBlob(ref(storage,`submissions/${d.owner}/${d.id}/manuscript`));const a=el('a','Download manuscript',{href:URL.createObjectURL(blob),download:'manuscript'});card.append(a);}catch{status.textContent='No manuscript attachment is available.';}}));card.append(actions);panel.append(card);}
 panel.append(el('h2','Drafts'));for(const d of drafts)panel.append(button(d.title,()=>editDraft(d)));
 panel.append(el('h2','Published'));for(const d of publications.filter(d=>d.state==='published')){const row=el('div',null,{class:'editorial-card'});row.append(el('strong',d.title),button('Edit',()=>editDraft({...d,id:d.id})),button('Withdraw',async()=>{if(!confirm('Withdraw this item from the website?'))return;await updateDoc(doc(db,'publications',d.id),{state:'withdrawn',publishedAt:serverTimestamp()});await dashboard();}));panel.append(row);}
}
async function editDraft(d){root.querySelector('#draft-editor')?.remove();draftId=d.id||doc(collection(db,'drafts')).id;const id=draftId;
 const choices=await fetch('/editorial/choices.json').then(r=>{if(!r.ok)throw Error('choices');return r.json();});
 const form=el('form',null,{id:'draft-editor'});form.append(el('h2','Prepare for publication'));select(form,'Type','kind',site.prefix==='/shalandi'?[['book','Book / publication'],['article','Article'],['comment','Comment']]:[['article','Article'],['comment','Comment']],d.kind||'article');
 field(form,'Title','title',{value:d.title||''});field(form,'Public byline','byline',{value:d.byline||'',max:120});field(form,'Approved text','body',{type:'textarea',value:d.body||'',max:60000});
 select(form,'Issue / collection','issue',choices.issues,d.issue||choices.issues[0]?.[0]);field(form,'Article path (comments only)','page',{value:d.page||'',required:false,max:300});
 const image=select(form,'Existing artwork / cover','image',choices.images,d.image||choices.images[0]?.[0]);const preview=el('img',null,{alt:'Selected publication artwork',width:'300',height:'200',class:'editorial-preview'});preview.src=image.value;image.onchange=()=>{preview.src=image.value};form.append(preview);
 const collect=()=>{const f=new FormData(form);return {kind:f.get('kind'),title:f.get('title').trim(),byline:f.get('byline').trim(),body:f.get('body'),issue:f.get('issue'),page:f.get('page').trim(),image:f.get('image')};};
 form.append(button('Save draft',async()=>{if(!form.reportValidity())return;await setDoc(doc(db,'drafts',id),{...collect(),sourceId:d.sourceId||'',updatedAt:serverTimestamp()});status.textContent='Draft saved privately.';await dashboard();}),button('Publish approved version',async()=>{if(!form.reportValidity())return;const data=collect();if(data.kind==='comment'&&!data.page.startsWith(site.prefix+'/')){status.textContent='Choose the article path for this comment.';return;}if(!confirm('Publish this approved text, byline and artwork? Contact details will stay private.'))return;const batch=writeBatch(db);batch.set(doc(db,'publications',id),{...data,state:'published',publishedAt:serverTimestamp()});batch.set(doc(db,'drafts',id),{...data,sourceId:d.sourceId||'',updatedAt:serverTimestamp()});if(d.sourceId)batch.update(doc(db,'submissions',d.sourceId),{status:'approved',updatedAt:serverTimestamp()});await batch.commit();status.textContent='Approved for publication. The website will update automatically, usually within 30 minutes.';form.remove();await dashboard();}),button('Close',()=>form.remove()));
 root.append(form);form.querySelector('input')?.focus();}
