import {getMagazineApp} from './app.js';
import {getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut,setPersistence,browserSessionPersistence} from 'firebase/auth';
import {getFirestore,doc,getDoc,getDocs,query,where,collection,limit,runTransaction,serverTimestamp,writeBatch} from 'firebase/firestore';
import {nextQuota} from './quota.js';

export async function mount(root,{page,title,shareControl}){
 const app=getMagazineApp(),auth=getAuth(app),db=getFirestore(app);
 const key=page.split('/').pop().replace(/\.html$/,'');
 const countRef=doc(db,'articleLikes',key);
 const el=(tag,text,attrs={})=>{const e=document.createElement(tag);e.textContent=text;for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);return e;};
 const actions=el('div','',{class:'response-actions'}),like=el('button','♡ ଭଲ ଲାଗିଲା',{type:'button','data-like':'','aria-pressed':'false'}),read=el('button','ମତାମତ',{type:'button','data-comments':'','aria-expanded':'false','aria-controls':'leave-comment'}),logout=el('button','Sign out',{type:'button',hidden:''}),status=el('p','',{role:'status'}),list=el('div','',{class:'response-list'});
 actions.append(like,read);if(shareControl)actions.append(shareControl);root.replaceChildren(actions,status);
 const details=el('section','',{id:'leave-comment',hidden:''}),summary=el('h3','ମତାମତ ଲେଖନ୍ତୁ'),form=el('form',''),label=el('label','ଆପଣଙ୍କ ମତାମତ',{for:'reader-comment'}),input=el('textarea','',{id:'reader-comment',required:'',maxlength:'2000',rows:'4','aria-describedby':'comment-note'}),note=el('p','ଆପଣଙ୍କ ମତାମତ ସମ୍ପାଦକଙ୍କ ଅନୁମୋଦନ ପରେ “ପାଠକ” ନାମରେ ପ୍ରକାଶ ପାଇବ । ନିଜ ଫୋନ୍ ନମ୍ବର ବା ଠିକଣା ଲେଖନ୍ତୁ ନାହିଁ । ଛୋଟ ପିଲାମାନେ ଅଭିଭାବକ ବା ଶିକ୍ଷକଙ୍କ ସହାୟତା ନିଅନ୍ତୁ ।',{id:'comment-note',class:'response-note'}),send=el('button','ପଠାନ୍ତୁ',{type:'submit'}),message=el('p','',{role:'status'});
 form.append(label,input,note,send,message);details.append(list,summary,form,logout);root.append(details);document.querySelectorAll('.ia-reading-end').forEach(e=>{if(e.querySelector('a[href*="kind=comment"]')&&e.querySelectorAll('a').length===1)e.hidden=true;});document.querySelectorAll('a[href*="kind=comment"]').forEach(a=>{a.href='#leave-comment';a.onclick=()=>{details.hidden=false;read.setAttribute('aria-expanded','true');input.focus();};});
 let liked=false,count=0;
 const render=()=>{like.textContent=(liked?'♥ ':'♡ ')+ 'ଭଲ ଲାଗିଲା'+(count?' · '+count:'');like.setAttribute('aria-pressed',String(liked));};
 async function login(){if(!auth.currentUser){await setPersistence(auth,browserSessionPersistence);await signInWithPopup(auth,new GoogleAuthProvider());}if(!auth.currentUser?.emailVerified)throw Error('verified');return auth.currentUser;}
 const error=e=>e.code==='permission-denied'?'Please slow down: up to 10 submissions and 60 like changes per hour. Your writing is still here.':e.code?.startsWith('auth/')?'Sign-in was not completed. Please try again; your comment is still here.':navigator.onLine?'Unable to save. Please try again in a minute. Your writing is still here.':'You are offline. Reconnect and try again; your writing is still here.';
 async function refresh(){const snapshot=await getDoc(countRef);count=snapshot.exists()?snapshot.data().count:0;render();}
 onAuthStateChanged(auth,async user=>{logout.hidden=!user;liked=false;render();if(user?.emailVerified){try{liked=(await getDoc(doc(db,'articleLikes',key,'readers',user.uid))).exists();render();}catch{status.textContent='Unable to load your like. Please try again.';}}});
 logout.onclick=()=>signOut(auth).catch(e=>status.textContent=error(e));
 like.onclick=async()=>{like.disabled=true;status.textContent='';try{const user=await login(),ref=doc(db,'articleLikes',key,'readers',user.uid);const result=await runTransaction(db,async tx=>{const quota=doc(db,'engagementLimits',user.uid);const [c,l,q]=await Promise.all([tx.get(countRef),tx.get(ref),tx.get(quota)]);tx.set(quota,nextQuota(q.data(),{article:key}));const next=(c.exists()?c.data().count:0)+(l.exists()?-1:1);tx.set(countRef,{count:next});if(l.exists())tx.delete(ref);else tx.set(ref,{at:serverTimestamp()});return {count:next,liked:!l.exists()};});count=result.count;liked=result.liked;render();}catch(e){status.textContent=error(e);}finally{like.disabled=false;}};
 read.onclick=async()=>{details.hidden=!details.hidden;read.setAttribute('aria-expanded',String(!details.hidden));if(details.hidden){status.textContent='';return;}read.disabled=true;status.textContent='Loading…';try{const snapshot=await getDocs(query(collection(db,'publications'),where('page','==',page),where('state','==','published'),limit(100)));const comments=snapshot.docs.map(d=>d.data()).filter(d=>d.kind==='comment'&&d.state==='published').sort((a,b)=>(a.publishedAt?.seconds||0)-(b.publishedAt?.seconds||0));list.replaceChildren();document.querySelectorAll('.ia-published .ia-comments').forEach(e=>e.hidden=true);for(const c of comments){const item=el('article','');item.append(el('strong',c.byline),el('p',c.body));list.append(item);}status.textContent=comments.length?'':'ନୂଆ ଅନୁମୋଦିତ ମତାମତ ନାହିଁ ।';}catch{status.textContent='Unable to load comments. Please try again.';}finally{read.disabled=false;}};
 form.onsubmit=async event=>{event.preventDefault();if(!input.value.trim()||!form.reportValidity())return;send.disabled=true;message.textContent='';try{const user=await login(),item=doc(collection(db,'submissions'));await runTransaction(db,async batch=>{const quota=doc(db,'submissionLimits',user.uid),q=await batch.get(quota);batch.set(item,{owner:user.uid,name:'ପାଠକ',contact:user.email,kind:'comment',title:title.slice(0,240),body:input.value.trim(),page,status:'received',consent:'editorial-review-v1',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.set(quota,nextQuota(q.data(),{id:item.id}));});input.value='';message.textContent='ମତାମତ ମିଳିଲା । ସମ୍ପାଦକଙ୍କ ଅନୁମୋଦନ ପରେ ପ୍ରକାଶ ପାଇବ ।';}catch(e){message.textContent=error(e);}finally{send.disabled=false;}};
 await refresh().catch(()=>status.textContent='Likes are temporarily unavailable. You can still read and share.');
}
